baseURL = 'https://xiaowenjictf.github.io/'
languageCode = 'en-us'
title = "xiaowenji's blog"
theme = "reimu"

disableKinds = ["RSS"]

[markup.highlight]
guessSyntax = true
noClasses = false

[caches]
  [caches.images]
    dir = ":cacheDir/images"
